name: Natalie Davis
author: Natalie Davis
url: https://nataliedavis.com.au
profilePic: /static/img/20240724-natalie-davis-finals-006.jpg
topContent: "# Deva is an Irish Creative Director and Designer whose skills
  range from strategy, branding, and design management to art direction,
  editorial, and experiential design. Currently based in Brooklyn, her work is
  informed by her experiences both brand and agency side. Previously, Deva
  worked at The Wing where she built and oversaw the creative department, and at
  Pentagram Design. Stuff"
bottomContent: "## In 2016 Deva founded For All Womankind and designed the
  now-iconic Femme Fists image that went viral globally during the Women's
  March.  Deva has earned awards from the Type Directors Club and Communication
  Arts and has spoken at Princeton University, AIGA, and Brand New Conference."
